# Generated by Django 5.2.7 on 2025-11-20 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomAdmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subjct',
            new_name='Subject',
        ),
    ]
