# Generated by Django 5.1.6 on 2025-04-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0003_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='joined_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
