# Generated by Django 5.1.6 on 2025-04-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0004_alter_userprofile_joined_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='services_history',
            field=models.TextField(blank=True, null=True),
        ),
    ]
