# Generated by Django 5.2.7 on 2025-11-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0007_alter_userprofile_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('teacher', 'teacher'), ('student', 'student')], default='user', max_length=10),
        ),
    ]
